### ISSUE TITLE
page titles in the admin pages listing not updated when switching language

### ISSUE THREAD

**Issue by sampq** [tractorcow/silverstripe-fluent#159] opened 2015-11-04 06:39 UTC
Hello,

Thanks for the module, it is a great one.

I am not sure if I did something wrong. In the admin when switching the language the page titles in the pages listing are not updated to the current language titles. When opening a page there is no problem the content corresponds to the current language.  

I have this issue using SS 3.2. The problem is not there with SS 3.1.13.

Hope you can help. Thx.

Sam

**Comment by webspilka** [comment] 2015-11-19 16:25
I had the same problem on SS 3.1.13.  Helped the page refresh after the change of language. 
But after upgrading to SS 3.2 page refresh does not help. Pages in the site tree are always displayed in the default locale

**Comment by Xarinor** [comment] 2015-12-09 15:56
I can confirm and reproduce this issue. Seems to be only visual as of the time being.
Or did anyone encounter functional issues while working with page titles?

**Comment by webspilka** [comment] 2015-12-09 19:40
Database is saved all right, just in admin when changing language site tree continues to be displayed in the default locale

**Comment by phptek** [comment] 2016-06-02 23:56
@webspilka are you sure it's the default_locale? What happens if you do the following:

Create a new page and immediately use the locale switcher to switch to a different (non-default) locale and enter some text, then save. Now switch to another non-default locale, if your problem is anything like mine, the field's default content as displayed in the CMS is the content I previously entered in the first (non-default) locale.

Make sense?

**Comment by webspilka** [comment] 2016-06-03 05:21
my problem disappeared after updating silverstripe-fluent, several months ago

**Comment by phptek** [comment] 2016-06-06 18:55
@webspilka OK, can you close this issue then to keep the list clean? :-)

**Comment by webspilka** [comment] 2016-06-07 09:43
@phptek, I can't, becose @sampq create this issue

**Comment by tractorcow** [comment] 2016-07-04 06:32
It's gone. :D

**Closed by tractorcow** 2016-07-04 06:32 UTC
