### ISSUE TITLE
Fluent and TagField or GridFields with Sort don't work well together.. or at all without workaround

### ISSUE THREAD

**Issue by chromos33** [tractorcow/silverstripe-fluent#427] opened 2018-06-13 08:45 UTC
Don't know if this is a duplicate with #208 but the problem is
When using Tagfield which internally Sorts by "Title" I get the error that Distinct and OrderBy requires "Title" to be in Select which augmentSQL overwrites.

Current workaround is to create a new Field that mirrors "Title" and Disable that Field for translating and set the Sort Field to that.

**Comment by tractorcow** [comment] 2018-06-15 01:39
It's another good use case to test, but it is a symptom of the same bug I'm afraid! =(

**Comment by tractorcow** [comment] 2018-06-15 01:39
Duplicate of https://github.com/tractorcow/silverstripe-fluent/issues/427

**Closed by tractorcow** 2018-06-15 01:39 UTC

**Comment by robbieaverill** [comment] 2018-06-15 01:50
Duplicate of #208?

**Comment by tractorcow** [comment] 2018-06-17 22:48
Oops yes wrong copy paste.
