### ISSUE TITLE
v4 SiteTree History not functioning with Fluent

### ISSUE THREAD

**Issue by chrispenny** [tractorcow/silverstripe-fluent#313] opened 2017-12-01 00:42 UTC
Possibly something to do with `augmentWrite()`? I haven't had time to look into this much further though unfortunately. Hopefully I can in the coming weeks.

- `Versioned::doRollbackTo()` calls `$owner->copyVersionToStage(...)`, which overrides our current `DRAFT` state.
- Immediately after that it calls `$owner->writeWithoutVersion();`.
- With Fluent installed, the content from `$owner` is written against the `DRAFT` state again.

Below I'm tracking the events that take place when `doRollbackTo()` is invoked. I log a message before and after each new method is called, and log any data within that method that is relevant.

```
Versioned::doRollbackTo(): calling "$owner->copyVersionToStage()"
Versioned::copyVersionToStage(): calling '$from->write()'

SiteTreeExtension::onBeforeWrite(): entered onBeforeWrite
SiteTreeExtension::onBeforeWrite(): Content: <p>Page version 1</p>

Versioned::copyVersionToStage(): finished '$from->write()'
Versioned::copyVersionToStage(): calling '$from->destroy()'
Versioned::copyVersionToStage(): finished '$from->destroy()'

Versioned::doRollbackTo(): finished "$owner->copyVersionToStage()"
Versioned::doRollbackTo(): calling "$owner->writeWithoutVersion()"

SiteTreeExtension::onBeforeWrite(): entered onBeforeWrite
SiteTreeExtension::onBeforeWrite(): Content: <p>Page version 3</p>

Versioned::doRollbackTo(): finished "$owner->writeWithoutVersion()"

```

Below are some screen shots of what is happening in the CMS. I published 3 new versions of the Page (these are Database Version numbers 2, 3, and 4), and i then rolled back to Database Version 2.

Database Version 2 published:
![screen shot 2017-12-01 at 10 39 49 am](https://user-images.githubusercontent.com/505788/33456476-71801a64-d684-11e7-9f9e-45223136b57c.png)

Database Version 3 published:
![screen shot 2017-12-01 at 10 39 57 am](https://user-images.githubusercontent.com/505788/33456493-78440fea-d684-11e7-8655-dac14be9c8ef.png)

Database Version 4 published:
![screen shot 2017-12-01 at 10 40 05 am](https://user-images.githubusercontent.com/505788/33456502-7c218be2-d684-11e7-9132-077c51d59053.png)

Rolling back to Database Version 2:
![screen shot 2017-12-01 at 10 40 22 am](https://user-images.githubusercontent.com/505788/33456512-819f0978-d684-11e7-973c-66519d2f93b5.png)

Rollback to Database Version 2 completed:
![screen shot 2017-12-01 at 10 40 31 am](https://user-images.githubusercontent.com/505788/33456520-865f03e6-d684-11e7-8778-347603244762.png)

Cheers :)

**Comment by robbieaverill** [comment] 2018-02-15 00:55
This is going to be fun.

**Comment by tractorcow** [comment] 2018-02-15 01:16
In the `$this->write()` in `copyVersionToStage` please capture the fluent-augmented $manipulation when doing the rollback.

What should happen is that all the localised rows for that record are re-created with the new version.

**Comment by tractorcow** [comment] 2018-02-15 01:18
Also please dump the rows (both SiteTree and SiteTree_Localised) before / after the rollback.

**Comment by robbieaverill** [comment] 2018-02-15 02:44
The first issue I'm investigating is that versions from other locales show up in the list (generated via `$page->allVersions();` in CMSPageHistoryController.

Set up steps:

* Create a page in default locale, publish
* Change content, publish
* Switch locale to another locale, adjust content and publish
* Change content, publish
* Switch back to default locale
* Go to history for page

You should see the original two published versions, but you also see the other locale's versions as well.

**Comment by robbieaverill** [comment] 2018-02-15 04:15
Here's the full SQL query that `$page->allVersions()` is running: https://gist.github.com/robbieaverill/d328c7da85d5160bb1aea7a74f80bff2

Context:

* Page ID: 11
* Current locale: en_US
* Two records exist in de_DE, and one exists from earlier in zh_CN

Results of query:

![image](https://user-images.githubusercontent.com/5170590/36240043-72f92018-1273-11e8-8484-c4527ef9705f.png)

Note that red boxes indicate version results that belong to locales other than en_US. Also there's a fixed `en_US` Locale column result in the SQL query, and the RecordID column returns 11 in all rows.

---

Tables (filtered by record ID):

**SiteTree:** 

![image](https://user-images.githubusercontent.com/5170590/36240056-8c1c9264-1273-11e8-9347-0b11984adc20.png)

**SiteTree_Localised:**

![image](https://user-images.githubusercontent.com/5170590/36240062-987a3d9a-1273-11e8-8731-6a06c8f6afaa.png)

**SiteTree_Localised_Versions:**

![image](https://user-images.githubusercontent.com/5170590/36240071-a35924d8-1273-11e8-9ab6-c24636b6b868.png)

**SiteTree_Versions:**

![image](https://user-images.githubusercontent.com/5170590/36240077-af1a06b6-1273-11e8-93f8-eac6d7c33fc6.png)

**Comment by tractorcow** [comment] 2018-02-18 21:09
I think this is the bug

```sql
FROM   `SiteTree_Versions`
  LEFT JOIN `SiteTree_Localised` AS `SiteTree_Localised_en_US_Versions`
    ON `SiteTree_Versions`.`ID` = `SiteTree_Localised_en_US_Versions`.`RecordID`
       AND `SiteTree_Localised_en_US_Versions`.`Locale` = 'en_US'
```

Should be

```sql
FROM   `SiteTree_Versions`
  LEFT JOIN `SiteTree_Localised_Versions` AS `SiteTree_Localised_en_US_Versions`
    ON `SiteTree_Versions`.`RecordID` = `SiteTree_Localised_en_US_Versions`.`RecordID`
    AND `SiteTree_Versions`.`Version` = `SiteTree_Localised_en_US_Versions`.`Version`
       AND `SiteTree_Localised_en_US_Versions`.`Locale` = 'en_US'
```

**Comment by tractorcow** [comment] 2018-02-18 21:13
@robbieaverill how did you dump https://gist.github.com/robbieaverill/d328c7da85d5160bb1aea7a74f80bff2? Normally the ORM produces double-quoted SQL not back-ticked ones.

**Comment by robbieaverill** [comment] 2018-02-18 21:17
@tractorcow I've switched it so I can run it in my MySQL client =)

**Comment by robbieaverill** [comment] 2018-02-18 21:19
Ok that example SQL change works for me but I also need to switch it for an inner join. We could add another `WHERE` clause instead and keep it as a left join - thoughts?

**Comment by tractorcow** [comment] 2018-02-18 21:47
Bug is in `FluentVersionedExtension::rewriteVersionedTables`. I'm not sure exactly what the fix will be, as I'll need to write some unit tests.

**Comment by tractorcow** [comment] 2018-02-18 23:27
Strange, I can see a `SiteTree_Localised` => `SiteTree_Localised_Versions` table rename being created, but it's not working.

**Comment by tractorcow** [comment] 2018-02-18 23:35
It is working, my code works. I'm not sure how you got your SQL ... it's incorrect and non-reproducable. see my comment on https://gist.github.com/robbieaverill/d328c7da85d5160bb1aea7a74f80bff2#gistcomment-2355188

**Comment by tractorcow** [comment] 2018-02-19 00:29
So apparently it's this
```
    public function doRollbackTo($version)
    {
        $owner = $this->owner;
        $owner->extend('onBeforeRollback', $version);
        $owner->copyVersionToStage($version, static::DRAFT, true);
        $owner->writeWithoutVersion();
        $owner->extend('onAfterRollback', $version);
    }
```

The `$owner->writeWithoutVersion()` overwrites the correctly rolled back version, with the current version, messing everything up.

**Comment by robbieaverill** [comment] 2018-02-19 00:41
Noting here that as discussed with @tractorcow the fact that history shows versions of a page across all locales is a feature, not a bug.

Perhaps in future we could add locale indicators to the list to show which locale they belong to.

cc @sachajudd @clarkepaul

**Comment by tractorcow** [comment] 2018-02-19 00:58
Fixed with https://github.com/silverstripe/silverstripe-versioned/pull/118

**Comment by tractorcow** [comment] 2018-02-19 00:59
@robbieaverill yeah on that issue I think a "show only version changes in this locale" could be a checkbox, or maybe a config?

**Closed** 2018-02-19 16:02 UTC
Labels: affects/v4, impact/high, type/bug
