### ISSUE TITLE
Domain not passed in functions

### ISSUE THREAD

**Issue by zrii** [tractorcow/silverstripe-fluent#171] opened 2015-11-26 13:24 UTC
I had a problem with setting domain per locale, since we had a couple of websites running different languages, one per domain.

The fix was hardcoded, didn't have the time to look where the functions are called for a pull request.

Fluent.php

``````php
public static function default_locale($domain = null) {
```
with
``````php
public static function default_locale($domain = true) {
```

AND

```php
public static function locales($domain = null) {
```
with
``````javascript
public static function locales($domain = true) {
```

Maybe if I have time I will make a pull request.

**Comment by tractorcow** [comment] 2015-11-26 19:57
I think @prij had an issue with a fix that she was going to push up for me. :) Still waiting! :D

**Comment by tractorcow** [comment] 2015-11-26 20:14
@zrii can you please describe what the bug was? You have given me the fix but not actually explained what necessitated it. :D

**Comment by tractorcow** [comment] 2015-11-26 20:15
If I recall correctly, the fix @prij was going to add was to set the parameter correctly in Fluent::current_locale 

```php
// Fallback to default if empty or invalid
$domainMode = <something>;
if(empty($locale) || !in_array($locale, self::locales())) {
	$locale = self::default_locale($domainMode);
}
```

**Comment by zrii** [comment] 2015-11-26 21:05
OK the issue was the following.
One website would be set on 3 languages on 3 domains, one domain each language (nl, en, sr, with according TLD .nl, .en, .rs), with default dutch language.

Settings are the following in fluentconfig.yml:

```yml
---
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  detect_locale: false
  default_locale: nl_NL
  locales:
    - nl_NL
    - en_US
    - sr_RS
  aliases:
    nl_NL: nl
    en_US: en
    sr_RS: sr
  force_domain: true
  domains:
    example.nl:
      locales:
        - nl_NL
      default_locale: nl_NL
    example.us:
      locales:
        - en_US
      default_locale: en_US
    example.rs:
      locales:
        - sr_RS
      default_locale: sr_RS
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: nl_NL
```

Then pages would be made. 
Example page would be example.nl/page-one. In English it would be example.us/page-one-english same page in different language and different url segment.
If you would visit home page of English, example.us/ and then go to example.us/page-one-english there would be no problem.

But if you would open incognito view and open example.us/page-one-english directly, you would get a 404 error. It would 'fix' if you visit homepage and it switches language and then go to the page example.us/page-one-english and get it.

That was the issue, the quick and dirty fix was my first post.

Hope I explained this well, and hopefully tomorrow I look into the code and the calls and do a proper fix on it.

**Comment by tractorcow** [comment] 2015-11-27 00:00
I think that looking at your issue, @prij's fix will solve it. :)

**Comment by dkriegner** [comment] 2016-02-11 17:15
I am afraid I hit the same issue. My site has two languages and two domains, which should be served by the two default locales.

Silverstripe 3.2.1 and config:
```
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  locales:
    - de_DE
    - cs_CZ
  domains:
    example.de:
      locales:
        - de_DE
        - cs_CZ
      default_locale: de_DE
    examplecs.cz:
      locales:
        - cs_CZ
        - de_DE
      default_locale: cs_CZ
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: de_DE
```

When I surf to the _de_-domain everything works just fine. When I surf to the _cz_-domain (in incognito mode/for the first time) the URL is rewritten to the _de_ domain and the german page is shown.

One can make the rewriting disappear by once surfing to _examplecs.cz/cs_CZ_ (or any other subpage). following visits will not rewrite the URL. However one problem remains also after:
The baseurl of the LocaleMenu is always the _example.de_ one. 

I use this template code:
```
      <% loop Locales %>
      <li>
       <a href="$Link.ATT" <% if $LinkingMode != 'invalid' %>rel="alternate" hreflang="$LocaleRFC1766"<% end_if %>><% if $Locale == $CurrentLocale %><u>$Title.XML</u><% else %>$Title.XML<% end_if %></a>
      </li>
      <% end_loop %>
```

any chance to see the fix of @prij ?

**Comment by tractorcow** [comment] 2016-02-11 21:04
It was merged in at https://github.com/tractorcow/silverstripe-fluent/commit/ceefc0a731585a1e296c85b0f0674e7b1e9e7d0d

I just noticed it wasn't in a tagged release yet, so I've added 3.4.0 https://github.com/tractorcow/silverstripe-fluent/releases/tag/3.4.0

**Comment by tractorcow** [comment] 2016-02-11 21:05
@dkriegner can you please confirm your site works with v 3.4.0? If so I'll close this ticket.

**Comment by dkriegner** [comment] 2016-02-12 07:23
@tractorcow  unfortunately 3.4.0 breaks the site (dev/rebuild) gives a server error. Is this expected to happen with SS v3.2.1? Or what is the correct way to make to test this (sorry rather new to SS)?

applying only the mentioned patch on top of fluent 3.2.1 does not change the issue.

**Comment by dkriegner** [comment] 2016-02-12 08:51
I should add some results of tests I did:

I think this issue has two manifestations: 
1) URL-rewriting: my observations show this does not occur in every browser. IE 11 and Firefox 44 seem not to have the URL rewritten, however, Chrome 48 has. Using Chrome 48 browsing to _examplecs.cz_ one ends up at _example.de_, directly loading a subpage prevents this behavior. So this seems to be a delicate issue.

2) Independent of point 1 all browsers, however, have the wrong baseurl when one browsers to the second domain specified in the config. Switching the domain definition in _fluent.yml_ all the behavior is switched between the two domains.

I should add that the used domain has a dash '-' in the domain name, e.g. _example-cs.cz_. can this cause troubles?

**Comment by prij** [comment] 2016-02-13 22:47
Hi @dkriegner, could you paste the contents of the fluent.yml file in the /fluent directory also?

**Comment by dkriegner** [comment] 2016-02-14 10:05
@prij: I did not touch it. so its the default:
[see here](https://github.com/tractorcow/silverstripe-fluent/blob/3.2.1/_config/fluent.yml)

**Comment by prij** [comment] 2016-02-14 11:33
@dhensby can you try using the fluent.yml of the latest version of Fluent -- if I recall correctly remember_locale and detect_locale were set to false by default as part of this fix.
Latest config is [here](https://github.com/tractorcow/silverstripe-fluent/blob/master/_config/fluent.yml)

Modified lines are [40 and 49](https://github.com/tractorcow/silverstripe-fluent/commit/94c38c405e33f082644f0de5205411e236633e6a).

Does the problem still persist after applying these updates and applying ?flush=all

**Comment by dkriegner** [comment] 2016-02-14 13:55
@prij I tried what you suggested. The behavior I now get consistently in all browsers is that when going to 

- **example.de** (first in config): site loads in german. $Link.ATT in the locale menu outputs absolute links as 'http://example.de' and 'http://example.de/cs_CZ/'. this is as expected
- **examplecs.cz** (second in config): site loads in czech. $Link.ATT in the locale menu outputs absolute links as 'http://example.de/' and 'http://example.de/cs_CZ/'. this is as before and not what i expected.
- loading the page directly from the **webhoster** (domain not in fluent config) resulted in a server error since i had no default_locale set in my fluent config. once i fixed this the page loads in the default_locale and $Link.ATT in the locale menu outputs relative links which seems fine.

**Comment by tractorcow** [comment] 2016-02-14 20:53
> unfortunately 3.4.0 breaks the site (dev/rebuild) gives a server error.

It would help a lot if you showed me that error!

**Comment by tractorcow** [comment] 2016-02-14 20:56
> When I surf to the cz-domain (in incognito mode/for the first time) the URL is rewritten to the de domain and the german page is shown.

Ok , maybe there is a problem with the domain matching. Are you perhaps going to www.examplecs.cz and not examplecs.cz? I don't think we have built in support for automatic subdomain matching. This would explain why the locale is getting matched incorrectly.

Maybe we need some kind of "ignore subdomains" option to filter the url before getting the configuration for that domain.

**Comment by tractorcow** [comment] 2016-02-14 21:06
I have a feeling that fixing the dev/build crash in 3.4.0 would allow you to use the latest version of the code, and make this problem a lot smaller. ;) It's hard to debug older versions, since we'd be unfairly including all the bugs that have been fixed in the newer versions.

@dkriegner if you could please include the output of the errors you spoke of I'll have a look at them.

**Comment by dkriegner** [comment] 2016-02-14 21:13
@tractorcow all "www" addresses are 301 redirected to the address without "www" via htaccess. But as I said this redirecting is not reproducible across browsers and currently i do not see it. i will try to get 3.4.0 running and come back to you to see if it changes the behavior described in my last comment.

**Comment by tractorcow** [comment] 2016-02-14 21:15
@dhensby neat, that would be great thanks!

**Comment by tractorcow** [comment] 2016-02-14 21:17
Maybe you could put some debugging info when testing to check what variables fluent believes to be the case; E.g. fluent::is_domain_mode(), Fluent::is_frontend(), Fluent::domains(true). If you could include the results of that in your reply that would help a lot thanks. :)

**Comment by dkriegner** [comment] 2016-02-14 22:15
Ok, no more problems with 3.4.0. I am not sure what the problem there was. i can only assume that some code was not uploaded correctly. Previously I also did not get any error I could report. it stopped during "Creating database records" of dev/build. Sorry for this wrong report.

Regarding the other debugging:
- **example.de** (first in config): site loads in german. $Link.ATT in the locale menu outputs absolute links as 'http://example.de' and 'http://example.de/cs_CZ/'. 

   - Fluent::is_domain_mode() -> true 
   - Fluent::is_frontend() -> true
   - Fluent::domains(true) -> {"example.de":{"locales":["de_DE","cs_CZ"],"default_locale":"de_DE"},"examplecs.cz":{"locales":["cs_CZ","de_DE"],"default_locale":"cs_CZ"}}

- **examplecs.cz** (second in config): site loads in czech. $Link.ATT in the locale menu outputs absolute links as 'http://example.de/' and 'http://example.de/cs_CZ/'. not what i expected.

   - Fluent::is_domain_mode() -> true 
   - Fluent::is_frontend() -> true
   - Fluent::domains(true) -> {"example.de":{"locales":["de_DE","cs_CZ"],"default_locale":"de_DE"},"examplecs.cz":{"locales":["cs_CZ","de_DE"],"default_locale":"cs_CZ"}}

- loading the page directly from the **webhoster** (not in fluent config): page loads in default_locale and $Link.ATT in the locale menu outputs relative links

   - Fluent::is_domain_mode() -> false
   - Fluent::is_frontend() -> true
   - Fluent::domains(true) -> []

**Comment by tractorcow** [comment] 2016-02-14 22:45
How about `Fluent::locales(true)`? I should have put this one in, because it'll indicate whether or not the correct locale is getting picked up.

**Comment by tractorcow** [comment] 2016-02-14 22:47
> loading the page directly from the webhoster

Do you mean via IP address? Sorry I'm not following here. :)

What we want is is_domain_mode() to be true in all cases on the live site; If it's false (as you've indicated) something bad is afoot!

**Comment by dkriegner** [comment] 2016-02-15 08:12
> How about Fluent::locales(true)? I should have put this one in, because it'll indicate whether or not the correct locale is getting picked up.

- **example.de**: ["de_DE","cs_CZ"]
- **examplecs.cz**: ["cs_CZ","de_DE"]
- **webhoster**: ["cs_CZ","de_DE"] 

as far as i can see thats always the order from the config.
> > loading the page directly from the webhoster

> Do you mean via IP address? Sorry I'm not following here. :)

Its not loading by IP since its a shared server but something like *subdomain.subdomain2.hoster.cz*

**Comment by tractorcow** [comment] 2016-02-15 20:25
Yep, it's definitely not filtering out the locales correctly from the hostname. I would expect that each hostname `Fluent::locales(true)` should only list the locales available in EACH domain. However, all are coming back.

It's almost as if the hostname isn't accessible to your application... it's not behind a web proxy is it? Is `$_SERVER['HTTP_HOST']` the correct name of your host?

I've been talking with @prij about this and will attempt to do some more in depth testing on this issue soon. I think this issue is high priority. :)

Thanks for getting back to me and helping me with debug information. Let me know if you can find the cause of the issue in the mean time.

**Comment by tractorcow** [comment] 2016-02-16 00:37
OK FOUND THE PROBLEM


```yaml
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  locales:
    - de_DE
    - cs_CZ
  domains:
    example.de:
      locales:
        - de_DE
        - cs_CZ
      default_locale: de_DE
    examplecs.cz:
      locales:
        - cs_CZ
        - de_DE
      default_locale: cs_CZ
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: de_DE

```

You have assigned both locales to both domains... you need to assign only the locales that domain SHOULD handle to that domain.

Change to the below to fix


```yaml
Name: myfluentconfig
After: '#fluentconfig'
---
Fluent:
  locales:
    - de_DE
    - cs_CZ
  domains:
    example.de:
      locales:
        - de_DE
    examplecs.cz:
      locales:
        - cs_CZ
---
Name: myfluenti18nconfig
After: '#fluenti18nconfig'
---
i18n:
  default_locale: de_DE

```

**Comment by tractorcow** [comment] 2016-02-16 00:39
@zrii 's problem was fixed in 3.4.0. :)

I think I need a validate method to fix this...

**Comment by tractorcow** [comment] 2016-02-16 02:17
I've pushed up a new helper `FluentValidateTask` to help check and spot these errors earlier. ;)

https://github.com/tractorcow/silverstripe-fluent/commit/469b8230ee736d70e88157e865e39cf449e8ced5

**Closed by tractorcow** 2016-02-16 02:17 UTC
Labels: bug

**Comment by dkriegner** [comment] 2016-02-16 08:34
@tractorcow thanks for pointing out my mistake. i will try your validator and maybe suggest some rephrasing in the documentation. I obviously did not understand this point from [here.](https://github.com/tractorcow/silverstripe-fluent/blob/master/docs/en/domain-configuration.md )

**Comment by tractorcow** [comment] 2016-02-16 22:18
Your documentation update was helpful, thanks!

**Comment by dkriegner** [comment] 2016-02-16 22:31
you are welcome. thanks for creating this!
