### ISSUE TITLE
Fluent + searchable integration

### ISSUE THREAD

**Issue by cheatus** [tractorcow/silverstripe-fluent#245] opened 2016-12-15 19:46 UTC
Hi @tractorcow ,
I've found that fluent isn't integrating with searchable module https://github.com/i-lateral/silverstripe-searchable. I don't know where to put a question, sorry if it's searchable thing. Basically fluent doesn't "see" few things at search results page, I mean language switcher isn't showing in my menu bar (loop Locales is ignored somehow) as well as url doesn't match to chosen language. But actual search query is recognized by fluent and I see translated search results. 

Silverstripe 3.4
Fluent 3.8.0
Searchable latest.

Any ideas why this is happening and is there any solution to this?

Cheers,
D.

**Comment by tractorcow** [comment] 2016-12-15 21:02
The problem is that fluent's query rewriting is very simple; It doesn't handle certain queries very well, especially those complicated ones as generated by search engines.

The solution is that someone needs to implement a SearchableFluentSearchAdapter (see https://github.com/tractorcow/silverstripe-fluent/blob/master/code/search/FluentSearchAdapter.php for the base interface).

This has been done for the core search functionality at https://github.com/tractorcow/silverstripe-fluent/blob/master/code/search/FluentMySQLSearch.php

**Comment by tractorcow** [comment] 2016-12-15 21:04
Regarding your search results page not showing the language filter, I'm sorry I haven't any idea. It may be something specific to Searchable that I'm not aware of.

**Comment by tractorcow** [comment] 2016-12-15 21:05
One problem is that fluent's query rewriting is very simple; It doesn't handle certain queries very well, especially those complicated ones as generated by search engines.

The solution is that someone needs to implement a SearchableFluentSearchAdapter (see https://github.com/tractorcow/silverstripe-fluent/blob/master/code/search/FluentSearchAdapter.php for the base interface).

This has been done for the core search functionality at https://github.com/tractorcow/silverstripe-fluent/blob/master/code/search/FluentMySQLSearch.php

**Comment by cheatus** [comment] 2016-12-16 11:55
Oh, I see thanks tho'. I'm not skilled enough to do this by myself I hope someone else could provide a good solution. Till then I work something out.

Cheers,
D.

**Comment by robbieaverill** [comment] 2018-07-02 04:04
Closing due to lack of attention in 18 months. Feel free to reopen if this is still an issue with part of the Fluent codebase =)

**Closed by robbieaverill** 2018-07-02 04:04 UTC
