### ISSUE TITLE
Cannot disable URL prefix on Link()

### ISSUE THREAD

**Issue by robbieaverill** [tractorcow/silverstripe-fluent#201] opened 2016-05-02 21:01 UTC
In some cases I've found it may be useful to be able to call `Page::Link()` and have it *not* add the locale alias prefix to the return, e.g.: `/en_NZ/my-pages/my-page/child-here`.

I'd like to be able to retrieve the locale-less page link in some situations (but not all!).

OK if I PR a config addition for it?

**Comment by wernerkrauss** [comment] 2016-05-03 06:25
This locale prefix - while it's totally handy - holds me off using fluent on an older translatable project. I don't want to change my current urls. Of course we need some logic to make URLs totally unique over all translations, when we don't have them seperated by the locale prefix.

**Comment by tractorcow** [comment] 2016-05-04 01:15
The older urls should still show the correct page, but new links to that page will have the prefix.

I guess I COULD re-consider allowing a "dont show prefix for default locales".... due to popular demand.

**Comment by tractorcow** [comment] 2016-05-04 01:18
Duplicate of https://github.com/tractorcow/silverstripe-fluent/issues/109 which I've now re-opened.

**Closed by tractorcow** 2016-05-04 01:18 UTC

**Comment by tractorcow** [comment] 2016-05-12 09:51
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/203
