### ISSUE TITLE
locale is added twice to urlsegment field when subpage

### ISSUE THREAD

**Issue by guyvanbael** [tractorcow/silverstripe-fluent#367] opened 2018-02-22 15:47 UTC
If a page has a parentpage, the locale is added twice. $Link however is ok.
<img width="959" alt="schermafbeelding 2018-02-22 om 16 46 05" src="https://user-images.githubusercontent.com/3098809/36548267-1e2d3d6c-17f0-11e8-9fb7-619ee92d36fe.png">

**Comment by robbieaverill** [comment] 2018-02-22 22:03
@guyvanbael can you please provide the version you're using? I can't reproduce this on 4.0.0-rc1:

![image](https://user-images.githubusercontent.com/5170590/36566704-1fc3ba4a-1889-11e8-97f5-c0d33e6230dd.png)

**Comment by guyvanbael** [comment] 2018-02-23 07:09
I'm using ss4.0.3 and for Fluent
"name": "tractorcow/silverstripe-fluent",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/tractorcow/silverstripe-fluent.git",
                "reference": "968c39dea28a6fc1b3760cd63315eea317f886d4"

**Comment by robbieaverill** [comment] 2018-02-25 21:53
Thanks, and could you please post a screenshot of the setup you have in the Locales tab?

**Comment by guyvanbael** [comment] 2018-02-26 11:24
<img width="1712" alt="schermafbeelding 2018-02-26 om 12 24 07" src="https://user-images.githubusercontent.com/3098809/36667950-fe9ce526-1aef-11e8-8974-219747e1c18c.png">

**Comment by robbieaverill** [comment] 2018-02-26 21:27
@guyvanbael this is the FluentFilteredExtension, yes? Are you applying it to SiteTree, Page, ?

**Comment by tractorcow** [comment] 2018-02-26 21:48
It's a regression from #348

We shouldn't be joining locale on top of the parent RelativeLink, which itself has the URL joined.

```
// $parentSegment could contain the locale's URL segment now. If we're in domain mode then remove it
        if ($domain && substr($parentSegment, 0, strlen($localeUrlSegment)) === $localeUrlSegment) {
            $parentSegment = ltrim(substr($parentSegment, strlen($localeUrlSegment)), '/');
        }
```

Instead of doing this entire check, it should assume (without doing risky string comparison) that the parent page includes the urlsegment.

**Comment by NightJar** [comment] 2018-03-05 03:11
I also have that hash checked out (it's the current `master` HEAD) and am also having trouble replicating this issue.
I think the issue must be related to serving from a subfolder (of the `DocumentRoot`). I'll try that.

**Comment by tractorcow** [comment] 2018-03-05 03:17
I can replicate it.

- turn off domains
- go to non-default locale
- create sub-page and edit it

![image](https://user-images.githubusercontent.com/936064/36956012-b16dd1c4-2090-11e8-8f37-d6765c01ccb0.png)

**Comment by tractorcow** [comment] 2018-03-05 05:01
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/369

**Closed** 2018-03-05 21:39 UTC
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug
