### ISSUE TITLE
Unable to set a translated field to an empty string.

### ISSUE THREAD

**Issue by bummzack** [tractorcow/silverstripe-fluent#156] opened 2015-10-26 10:47 UTC
If a user changes the field value of a "translation" to be empty, the default value gets copied over.

Example:
Fluent is configured with 3 Languages, DE, FR, IT, where DE is the default.
User edits a Page and fills in content for all 3 languages (say in the "Title" and "Content" field).

Now if the user wanted to remove the content in any of these languages (eg. selecting "Italian" and then deleting all the content inside the "Content" field), the content will then be reset to another language.

I know that this is probably due to a fallback mechanism in case a field isn't translated, but it makes for a very weird experience for CMS users (if they want the field value to be empty, they have to enter whitespace).

I guess this is a tricky problem to solve. Maybe a configuration-option to disable the fallback could be introduced? Maybe even on a "per field" level?

**Comment by tractorcow** [comment] 2015-10-27 22:29
This is one of the weaknesses in the system; It's impossible to have a "translation" that's an empty string, unless you set the default translation to empty as well.

One per field flag would double the number of db fields, which is already a bottleneck.

When https://github.com/tractorcow/silverstripe-fluent/pull/120 is finished and merged, you'll be able to reset translations to the default, which will support emptying all translations at the same time.

But as far as I can tell, having one locale with an "empty" value when the default has a non-empty value is impossible, and will likely always be impossible. :)

**Comment by oetiker** [comment] 2015-10-27 22:42
couldn't there be a difference between NULL and an empty string ? non assigned translations would be NULL while empty ones would be an empty string.

**Comment by tractorcow** [comment] 2015-10-27 22:50
That distinction is controlled by the ORM. It would require overriding the core functionality in a way that would likely break other core functionality. All empty strings are set to null before writing to the database, by default. E.g. queries that select empty string via `"Value" IS NULL` will no longer match values where we have rewritten null to empty strings.

**Comment by oetiker** [comment] 2015-10-27 22:55
oh how sad ... so yet another option would be to use in-band signaling with a special 'magic' string that gets inserted as an entry is emptied ...

**Comment by tractorcow** [comment] 2015-10-27 22:57
Very sad. :)

I'm sure there's a solution out there somewhere.

I should just make this module postgres-only and then use their json column type with no restrictions. :P

**Comment by tractorcow** [comment] 2015-10-27 22:59
Maybe the "use empty strings" could be a config you could turn on if you are sure your project works with this core feature changed.

**Comment by bummzack** [comment] 2015-10-28 07:12
Yeah, I was thinking about a config-flag. Not additional DB-Fields. Same goes for the per-field configuration, eg. something similar to the `translate` array in the config.

Example:
```
MyDataObject:
  extensions:
    - FluentExtension
  translate:
    - Title
    - Content
  no_fallback:
    - Content
```

**Comment by oetiker** [comment] 2015-10-28 07:22
a radical thought ... how about using json to store the translations anyway ... instead of having a separate field for each language, just have one extra for each translated field and store the translations in json. Database support is not really necessary. For searching, I would treat the json as text and then filter the results by decoding the matching content.

This would have the distinct advantage of being more flexible in what you store and also the number of extra columns would be restricted to just a single one per translated field.

**Comment by bummzack** [comment] 2015-10-28 07:54
@oetiker Sounds like an interesting approach, but would lead to a lot of implications. With SilverStripe 4.0 there will be an overhaul in file handling, which will remove the need that assets are stored locally (amongst other improvements). I fear that it might slow things down quite a bit if translations have to be fetched from a remote filesystem? Or it would introduce another layer of caching. Storing these JSON files somewhere else (eg. not the Database and not the SilverStripe "filesystem") will make backups and deployment more complicated.

**Comment by bummzack** [comment] 2015-10-28 07:56
@oetiker Ah I think I misinterpreted your post. You were talking about storing JSON data inside a DB field, right?

**Comment by oetiker** [comment] 2015-10-28 10:00
exactly :-) modern versions of postgresql has a special data type for this, but one could also just serialize the data structures into json and store them in a text field. There is good json support available for php and a fallback pure php version of the json encoder/decoder also exists to make sure this works across the board.

**Comment by tractorcow** [comment] 2015-10-28 20:48
>   how about using json to store the translations anyway

Unfortunately we wouldn't be able to do query-rewriting in connectors other than postgres, since it involves rewriting conditions as well as write queries. How would you `select (column in json content) as Content` in mysql? Fluent doesn't have control over the model layer, only the query layer.

Your approach would require a fluent db connector which did the necessary encoding inside an SS_Query subclass. Very hard to do...

I really like postgres though. ;)

**Comment by tractorcow** [comment] 2015-10-28 20:50
> Yeah, I was thinking about a config-flag. Not additional DB-Fields. Same goes for the per-field configuration, eg. something similar to the translate array in the config.

If this was the case, adding fluent to an existing site would cause pages with blank content for every non-default locale.

It would also mean that you would have to change a page in every locale if you wanted to rename something, not just in the default locale.

It's still worth thinking about though.

Tough nut to crack...

**Comment by uniun** [comment] 2015-12-18 13:53
> If this was the case, adding fluent to an existing site would cause pages with blank content for every non-default locale.

But usually the next step is to enter content for the new locale... Why would you need to add locale and keep the content the same?

> It would also mean that you would have to change a page in every locale if you wanted to rename something, not just in the default locale.

And it's OK. At least Title, MenuTitle, URLSegment, Content, Siteconfig.Title (and most of the custom columns) usually are different in every language. At least in our projects :)

I understand that we need this fallback for Title, MenuTitle, URLSegment and SiteConfig object - they should not be empty. But for Content or custom DB field it would be very useful to have an ability to disable fallback.
It wouldn't solve the issue but it would be something :)

**Comment by tractorcow** [comment] 2015-12-21 01:06
> But usually the next step is to enter content for the new locale... Why would you need to add locale and keep the content the same?


Because then you run into the risk where parts of your site have "forgotten" to be translated, and the currently exists no auditing mechanism to detect those pages.

Maybe it's ok if you limit your translation to only a small number of fields, or have a very small website.

**Comment by Friksel** [comment] 2016-05-09 18:04
Unfortunately I'm having the same problem with empty fields. I changed locale-fields directly in mysql to  `NULL`     `''` (empty string)   `' '` (string with one or more spaces)     `<p>  </p>` (paragraph with or without one or more spaces)   or even  `<p>&nbsp;</p>` (where the spacechar will not be interpreted, but exactly displayed) .... But while saving the page after that from inside the CMS, the fields are emptied again (while no field is touched) and the default locale-field is also set again...

Rightnow I'm thinking of just entering a dot inside each field where I just want no translation and then add functions to the controller to remove the dot again but I think that's ridiculous.

I see this issue is already an old one. Anybody came up with a solution to this? Or is there by any chance a fix coming up?

**Comment by tractorcow** [comment] 2016-05-10 23:29
Ok, so let's think about how the API would look.

What we need is a way of saying (either for a model, or a subset of fields) that translations should never fall back to the default locale. That is, they must be explicitly set, otherwise they will be blank.

Should we declare these the same way as `translate` is defined, as a simple list of fields for each model? Another way to do it is to allow `translate` config to take options for each value.

It would probably be ok as long as you didn't define important fields (e.g. Title, URLSegment) since the result of those being empty would cause the site to break.


Example:


```php
class Page extends SiteTree {
	private static $db = [
		'Header' => 'Text',
		'Description' => 'Varchar(255)',
	];
	private static $translate = [
		'Header' => [
			'inherited' => false // Header will not inherit from default translation
		],
		'Description', // defaults to inherit from default translation
	];
}
```

Thoughts? :P

**Comment by tractorcow** [comment] 2016-05-10 23:56
Ok, so I thought about how we could _try_ to hack in control of the null behaviour.

```php
class Page extends SiteTree {
    private static $db = [
        'Header' => 'Text',
        'Description' => 'Varchar(255)',
    ];
    private static $translate = [
        'Header' => [
		'emptifyNulls' => true, // when saving in current locale, nulls are converted to empty strings
		'inherited' => true, // Inherited, but because emptifyNulls is set, will only inherit nulls
        ],
        'Description', // defaults to inherit from default translation
    ];
}
```

**Comment by Friksel** [comment] 2016-05-11 09:29
@tractorcow  That seems like a very flexible solution. 

Just to sum thing up a little bit:

**flavours**
So, it seems like there are two flavour-'camps':
A) automation: Use default locale-values when there is no translation. 
        This can cause unexpected results and how to leave fields empty?
        But we can be sure there is at least always some visible text, although sometimes not in the right locale.
B) no automation: Leave untranslated (empty) fields empty. There is just no translation of empty fields. No confusion, 'cause what you see is what you get.

**suit both flavours**
I'm definitely on flavour B, so if you asked me I'd say take out the inheriting system. It's causing this trouble and questions in the first place and I think we should just trust the content-editors to check their work in draft mode before publishing. If they don't want a translation and therefore leave a field empty, leave it empty. Why show content in the wrong locale? That can even be very bad, showing content that is not supposed to be seen. But these are just my two cents.
I understand the other flavour and why you like that and it can suit other situations fine two.

I also understand there are some fields, like Title, MenuTitle and URLSegment that needs to have a value in order to keep functioning.

`InheritDefaultFields`
So your solution is very flexible and suits both flavours. Wich is great. I think we could even simplify this more. Why not combine these two settings into one setting inside fluent.yml: `InheritDefaultFields: true`. So basically saying: I go with flavour A (`true`) or I go with flavour B (`false`).
Where this setting does not influence the behaviour on Title, MenuTitle and URLSegments to prevent the website to break.

With this behaviour:
- set to `true`: Default behaviour. --> Only having to solve how to leave a translation empty
- set to `false`: there will be no inheriting/auto behaviour at all. What you see is what you get --> having to solve how to prevent Titles, MenuTitles, URLSegment to be left empty to prevent breaking

Then we don't need to add a header to all $translate's in our models/pages, wich we will set to the same values per website most, if not, all of the time. And may even use another field inside the db-record? We can then adjust the flavour in one place with one line and leaving all other code the same.

`how to leave a field empty?`
Nice to be able to set a field to NULL to prevent inheriting. But how can that be done from the CMS by a content-editor? I think leaving one or more space in the field to prevent inheriting will be just fine and worked as expected. It just don't seem to work right now, so it needs fixing I guess.
If everything else fails, as an alternative way to leave out fields from inheriting and keep them empty, would be to leave fields with a keyword empty, like [[[EMPTY]]]. Not really clean though.

**conflicts with auto MenuTitle**
Yesterday I worked for hours on translating all Titles on a website I'm working on, using the auto-fill of MenuTitle of the Silverstripe core. That showed in the CMS as expected and looked great. 
Then, after hours, I found out the frontend output was different then the field previews inside the CMS. Titles were overwritten by translated titles in other locales, probably the last locales I'd edited. To be honoust, sometimes I really wonder how other people can work with/around these issues in the real world.

Then I found this issue: https://github.com/tractorcow/silverstripe-fluent/issues/138
Here I read that this issue is solved in the DEV version. Now you gave me the strong advise to stick with the latest release and not switching to DEV. So at the moment I'm confused wich to pick, 'cause it seems like both versions having strong issues.

**new release? use dev or release?**
I'm sorry to sound a little pushy, but although I really like this module, rightnow this is taking me a lot of time to fix / workaround that stops me from doing other important stuff. 
Although I understand you are probably very busy in the moment for things like Silverstripe 4 too.

I'm working in the latest release version, because you gave me the strong advise to stick with that instead of switching to the dev version. But now I'm confused wich version is better. Both seem to have unexpected behaviour in core functionality.
Could you please tell me wich version has the least oddities/sideeffects? 
And will there by any chance be a new release from this dev with fixes any time soon? 

Thanks again!

**Comment by bummzack** [comment] 2016-05-11 09:36
@Friksel I'm also in the camp of people who are in favor of "no automation", but something you shouldn't forget is that `en_US` and `en_GB` are two different locales that won't diverge on every translation… maybe even on a minority of translations. So for these cases the automation as it is now is really helpful!

Therefore I'm all for a customizable approach that allows toggling inheritance from the default locale on a per-field level (not including the required fields such as the URLSegment)

**Comment by Friksel** [comment] 2016-05-11 10:20
I didn't think about it that way @bummzack . Funny how many perspectives on the same thing there can be. 
I agree on having a customizable approach, as long as this doesn't unnecesary complicate things or cost performance. 

But I don't understand your per-field wish. Isn't the automation system not exactly what you want then? You have en_US per default and if you'd like to change texts that are different in en_GB you enter a translation in en_GB, right?

**Comment by bummzack** [comment] 2016-05-11 10:51
@Friksel I just made the `en_US` and `en_GB` example to show where the automatic default translation makes a lot of sense. That's why I'm in favor of a configuration based approach, so that the default is the current system, but you can disable inheritance via config (as outlined by @tractorcow above)

**Comment by tractorcow** [comment] 2016-05-12 03:02
> I'm sorry to sound a little pushy, but although I really like this module, rightnow this is taking me a lot of time to fix / workaround that stops me from doing other important stuff.

It's a pain I share... and I regret my inability to spend more time helping with this issue.

I see the solution as more as an incremental fix... we can look at solving the easy problems, and develop more complicated "failover" logic further on down the line. I like the idea of starting with small incremental solutions, as it allows users to test and adapt, and give feedback during development, rather than a wizz-bang solution that pretends to solve everything, but may not really.

The hope is that we can find the smallest solution that makes the most benefit to the users. :)

Thanks very much @Friksel for the effort you've put into thinking about the solution.

> Although I understand you are probably very busy in the moment for things like Silverstripe 4 too.

I'm tagging alpha1 as we speak. :D

> @Friksel I'm also in the camp of people who are in favor of "no automation", but something you shouldn't forget is that en_US and en_GB are two different locales that won't diverge on every translation… maybe even on a minority of translations. So for these cases the automation as it is now is really helpful!

A possible future enhancement is to restrict inhert to certain locales (e.g. en_GB inherits from default en_US, but not es_ES). As with incremental changes, I'd like to start with the simple `on/off` option for now and see how necessary such an enhancement is.

**Comment by Friksel** [comment] 2016-05-13 10:56
@bummzack ah, I see. No worries.

> I like the idea of starting with small incremental solutions, as it allows users to test and adapt, and give feedback during development, rather than a wizz-bang solution that pretends to solve everything, but may not really.
Me too.

> I'm tagging alpha1 as we speak. :D
Good news. It feels like it is Christmas!

> The hope is that we can find the smallest solution that makes the most benefit to the users. :)
Can't wait ;)

> A possible future enhancement is to restrict inhert to certain locales (e.g. en_GB inherits from default en_US, but not es_ES, which should be blank if untranslated).
Going for the golden medal! Then we can serve Dutch and Flamish too, and German-german and Swiss-German :) Although, for me now, I'm glad if I finished just the base translations for this website ;)

> As with incremental changes, I'd like to start with the simple on/off option for now and see how necessary such an enhancement is.
That would be great!

**Comment by tractorcow** [comment] 2016-05-16 06:23
I suppose we could even have multiple defaults.... if you have two variants of german and two variants of english, you want to have a separate default for each, right?

**Comment by Friksel** [comment] 2016-05-20 16:43
For my project it's not necesary @tractorcow , but I understand the need and I guess that's the conclusion now if you'd like to support realistic situations around the world for sites serving a lot of translations/locales. Would be a kickass module then ;)

**Comment by Friksel** [comment] 2016-05-20 17:08
BTW in case the system gets converted into being able to have multiple locale-defaults, this could maybe be combined with the following issue/feature request for better SEO:

https://github.com/tractorcow/silverstripe-fluent/issues/205

**Comment by phptek** [comment] 2016-06-13 22:58
Just to add my 2c worth (I'll need to re-read again to get my head around the inheritance discussion).

## Workaround ##

The fugly "solution" mooted above to work around the inability to truncate a field, and on a field-by-field basis in my project is to use `__get()` on Page.php and check if the length of the request field is >= 2 and only then, show it in the frontend template:

```php
    /**
     * This is a workaround while we sort out what's wrong with the Fluent module.
     * See: https://github.com/tractorcow/silverstripe-fluent/issues/204
     *
     * The workaround for CMS authors is to insert a space character, then Save & Publish. All we do here is ensure
     * that the field length is >=2 before showing it, rather than PHP-falsey as the framework does by default.
     *
     * @param string $field
     * @return mixed|null
     */
    public function __get($field) {
        // Perform a specific check on translated fields
        if (in_array($field, $this->config()->translate)) {
            return strlen($this->getField($field)) >=2 ? $this->getField($field) : null;
        }

        return parent::__get($field);
    }
```

...but of course not only is this fugly, it's a performance issue and _may_ cause problems for SS itself from `ViewableData`'s perpective (where SS' own `__get()` logic lies)

## JSON Storage ##

I have mooted this before, but looking at @tractorcow 's response above, he seems to assume that any JSON solution would require native JSON ORM queries (MySQL 5.7 also supports native JSON storage, but uses different query operators) which no SS DB adapter support yet (AFAIK)

Because I've been encountering problems that are best solved using a JSON storage solution, I wrote (and am still working on) [SilverStripe JSONText](https://github.com/phptek/silverstripe-jsontext) which _may_ prove useful when more feature complete for Fluent going forward.

Keen to start a discussion but best for another ticket :-)

**Comment by tractorcow** [comment] 2016-06-16 03:46
Haha, that's a nice hack. :)

My goal for this is to still add the "disable-inheritance" option for specific fields, but has to wait until I get time.

**Comment by phptek** [comment] 2016-06-16 05:04
Can you see your way to creating an enhancement issue, describing in graphic detail, what you propose? Then someone else can have a crack at it.

**Comment by tractorcow** [comment] 2016-07-07 06:27
Workaround!!

If https://github.com/tractorcow/silverstripe-fluent/pull/217 is merged, then you can just do `$myPage-> copyFieldsToLocale(Fluent::default_locale());` and it will sync. :)

**Comment by tractorcow** [comment] 2016-07-07 06:29
Edit: My workaround doesn't address this problem after all. :)

**Comment by tractorcow** [comment] 2016-09-15 23:51
Finally finally addressed this issue at https://github.com/tractorcow/silverstripe-fluent/pull/225.

Sorry to leave this for ~1 year. =(

**Closed** 2016-09-16 04:42 UTC
Labels: bighardbutwouldlike
