### ISSUE TITLE
Fluent breaks SiteTree Batch Actions

### ISSUE THREAD

**Issue by NightJar** [tractorcow/silverstripe-fluent#433] opened 2018-06-29 01:53 UTC
500 Server error while attempting to publish in what I would have thought to be a somewhat common workflow:

1) Create a locale.
2) Visit your site to observe `The requested page could not be found.` (nothing is published).
3) Visit `admin/pages`
4) choose Batch Actions above the site tree on the left
5) Select every page's corresponding tickbox
6) Select the `Publish` action from the `Choose an action...` dropdown
7) Click `Go` from the batch actions interface
8) Click `OK` on the `confirm` javascript dialog
8) Observe a red accented `Internal Server Error` toast notification in the top right of the CMS.

```
ERROR [Emergency]: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:

SELECT DISTINCT "SiteTree_Versions"."ClassName", "SiteTree_Versions"."LastEdited", "SiteTree_Versions"."Created", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."URLSegment"
	ELSE "SiteTree_Versions"."URLSegment" END
 AS "URLSegment", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."Title"
	ELSE "SiteTree_Versions"."Title" END
 AS "Title", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."MenuTitle"
	ELSE "SiteTree_Versions"."MenuTitle" END
 AS "MenuTitle", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."Content"
	ELSE "SiteTree_Versions"."Content" END
 AS "Content", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."MetaDescription"
	ELSE "SiteTree_Versions"."MetaDescription" END
 AS "MetaDescription", "SiteTree_Versions"."ExtraMeta", "SiteTree_Versions"."ShowInMenus", "SiteTree_Versions"."ShowInSearch", "SiteTree_Versions"."Sort", "SiteTree_Versions"."HasBrokenFile", "SiteTree_Versions"."HasBrokenLink", CASE
	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN "SiteTree_Localised_en_NZ"."ReportClass"
	ELSE "SiteTree_Versions"."ReportClass" END
 AS "ReportClass", "SiteTree_Versions"."Version", "SiteTree_Versions"."CanViewType", "SiteTree_Versions"."CanEditType", "SiteTree_Versions"."ProvideComments", "SiteTree_Versions"."ModerationRequired", "SiteTree_Versions"."CommentsRequireLogin", "SiteTree_Versions"."ParentID", "SiteTree_Versions"."RecordID" AS "ID", 
			CASE WHEN "SiteTree_Versions"."ClassName" IS NOT NULL THEN "SiteTree_Versions"."ClassName"
			ELSE 'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName", "SiteTree_Versions"."RecordID", "SiteTree_Versions"."WasPublished", "SiteTree_Versions"."WasDeleted", "SiteTree_Versions"."WasDraft", "SiteTree_Versions"."AuthorID", "SiteTree_Versions"."PublisherID", 'en_NZ' AS "Locale", CASE 	WHEN "SiteTree_Localised_en_NZ"."ID" IS NOT NULL THEN 'en_NZ' 
ELSE NULL END AS "SourceLocale"

FROM "SiteTree_Versions"
INNER JOIN             (
           
SELECT "SiteTree_Versions"."RecordID",
                MAX("SiteTree_Versions"."Version") AS "LatestVersion"
           
FROM "SiteTree_Versions"
           
WHERE "SiteTree_Versions"."WasDeleted" = 0
           
GROUP BY "SiteTree_Versions"."RecordID"
            )                                 AS "SiteTree_Versions_Latest" ON             "SiteTree_Versions_Latest"."RecordID" = "SiteTree_Versions"."RecordID"
            AND "SiteTree_Versions_Latest"."LatestVersion" = "SiteTree_Versions"."Version"
LEFT JOIN "SiteTree_Localised_Versions" AS "SiteTree_Localised_en_NZ" ON "SiteTree_Versions"."RecordID" = "SiteTree_Localised_en_NZ"."RecordID" AND "SiteTree_Localised_en_NZ"."Locale" = ? AND "SiteTree_Localised_en_NZ"."Version" = "SiteTree_Versions"."Version"

WHERE ("RecordID" IN (?, ?, ?, ?, ?, ?))
 AND ("SiteTree_Versions"."WasDeleted" = ?)

ORDER BY "SiteTree_Versions"."Sort" ASC

Column 'RecordID' in where clause is ambiguous
IN POST /admin/pages/edit/batchactions/publish
```

**Comment by robbieaverill** [comment] 2018-06-29 01:54
Duplicate of https://github.com/tractorcow/silverstripe-fluent/issues/379 =)

**Closed by robbieaverill** 2018-06-29 01:54 UTC

**Comment by RoyalPulp** [comment] 2021-01-12 20:59
Just got the same problem... "The requested page could not be found." after Upgrading  from SS3 to SS4 , after creating Locales in the backend


Fluent has been so much easier and more consistent for SS3... (database scheme is better now... )
Configuration with a config-file was really preferable  to the Backend-approach... 
Takes so much more time now to get a system working
