### ISSUE TITLE
Using standard SearchForm fails

### ISSUE THREAD

**Issue by sanderha** [tractorcow/silverstripe-fluent#404] opened 2018-04-17 09:36 UTC
Maybe I missed something, but I get this error when trying to do a normal search, with the search form:
```
[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SELECT DISTINCT count(*) FROM "SiteTree" WHERE ( MATCH (Title, MenuTitle, Content, MetaDescription) AGAINST ('Jobs*' IN BOOLEAN MODE) + MATCH (Title, MenuTitle, Content, MetaDescription) AGAINST ('Jobs*' IN BOOLEAN MODE) AND ShowInSearch 0) AND (("SiteTree_Localised_da_DK"."ID" IS NOT NULL)) 42S22-1054: Unknown column 'SiteTree_Localised_da_DK.ID' in 'where clause'
```

I've enabled `\SilverStripe\ORM\Search\FulltextSearchable::enable();` and use ` $SearchForm` in templates.

I also have this active:
```yml
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentFilteredExtension'
```

I'm running SS4.1 and Fluent 4.0.2.

**Comment by DorsetDigital** [comment] 2018-08-21 20:47
I think this is a duplicate of #360 

Has there been any movement on this issue?   Unless I've missed something, currently the only option for having search on a site using Fluent is to deploy an external search like Solr  :-(

**Comment by robbieaverill** [comment] 2018-08-21 20:59
Thanks @DorsetDigital @sanderha - yeah this looks like a duplicate issue, let's focus on #360

**Closed by robbieaverill** 2018-08-21 20:59 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
