### ISSUE TITLE
Translation not from default language

### ISSUE THREAD

**Issue by brokemeisteratwork** [tractorcow/silverstripe-fluent#426] opened 2018-06-12 08:38 UTC
Hi everyone!

We want to translate our main page (DE) into several main lanuage (e.g. FR, EN), afterwards we want to roll out the translations into countries, reusing the translations.

e.g.
main translation
de_DE -> fr_FR
Now I want to reuse it for CH
de_DE -> de_CH => no problem
fr_FR -> fr_CH =>the text field auf the DE content, but I would like to use fr_FR, because I don't want to copy every again into silverstripe. Only one field is different between fr_FR and fr_CH.

Is it possible? I tried serveral things ways to solve this scenorio. Perhaps I have missed something in the configuration/docs...

**Comment by tractorcow** [comment] 2018-06-12 22:12
If you want to setup a custom query for a specific field, you can add the raw SQL to an extension on your model.

By default the query for each field will follow the failover chain for each locale. You should set these up for each locale based on where to draw content from for un-localised pages.

E.g. US will failover to Spanish, or failing that chinese, if non-localised.

![image](https://user-images.githubusercontent.com/936064/41320002-f694fd5e-6ef1-11e8-9209-e4eec960d6b1.png)

If you look in FluentExtension::localiseSelect() you can see the logic that is built by fluent to select each field.

you can replace this with your own field-dependant logic via updateLocaliseSelect extension in your model. With this logic you can, for example, force a specific field to always fail over to fr_FR, even if it exists in fr_CH or de_DE (the parent locale).

**Comment by tractorcow** [comment] 2018-06-12 22:13
Closing as this is a question not a bug. :) I can still discuss the question here with you if you like though.

**Closed by tractorcow** 2018-06-12 22:13 UTC
