### ISSUE TITLE
When installing with composer, got his error: Could not parse version constraint MailChimp.php: Invalid version string "MailChimp.php"

### ISSUE THREAD

**Issue by alfredoyong** [tractorcow/silverstripe-fluent#368] opened 2018-02-23 22:07 UTC
Using composer to install the module:

`composer require tractorcow/silverstripe-fluent ^4`

got this error:

`[UnexpectedValueException]`
` Could not parse version constraint MailChimp.php: Invalid version string "MailChimp.php"`

**Comment by robbieaverill** [comment] 2018-02-24 01:18
Can you share your composer.json file? This problem is not caused by fluent so closing, but happy to help you anyway

**Closed by robbieaverill** 2018-02-24 01:18 UTC

**Comment by alfredoyong** [comment] 2018-02-26 14:30
Thank you so much again! 
this is it:
```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.0.0@stable",
        "silverstripe-themes/simple": "~3.2.0"
    },
    "require-dev": {
        "phpunit/PHPUnit": "^5.7"
    },
    "extra": {
        "project-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "mysite/.htaccess",
            "mysite/_config.php",
            "mysite/_config/mysite.yml",
            "mysite/code/Page.php",
            "mysite/code/PageController.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

```

**Comment by alfredoyong** [comment] 2018-02-28 15:27
Just in case somebody have a similar problem... 
installing with this sentence generated the problem: 

`composer require tractorcow/silverstripe-fluent ^4`

But, this one did the trick:

`composer require tractorcow/silverstripe-fluent master`
